version: "3.9"

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5671:5671
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  
  subscriptions_api:
    build: .\CryptoScan.Subscriptions.API
    ports: 
      - 8001:80
    
  web:
    build: .\CryptoScan.Web
    ports: 
      - 8002:80
    environment:
      - RabbitMQ__HostName=rabbit
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=user
      - RabbitMQ__Password=password
  
  messaging_service:
    build: .\CryptoScan.Messaging.Service
    ports:
      - 8004:8080
    environment:
      - spring_rabbitmq_host=rabbit
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=user
      - spring_rabbitmq_password=password